# ==============================================================================
# ACTUAL BUDGET STREAMLIT DASHBOARD (PARAMETERIZED)
# ==============================================================================
# 
# STEP 0: This container needs https://github.com/jhonderson/actual-http-api running for REST API calls.
#
# STEP 1: In the mounted directory create secrets.toml file
#
# STEP 2: Paste the following TOML template into the file and update the 
#         API keys/URLs. This file controls all dashboard math and logic:
#
# ----------- COPY BELOW THIS LINE -----------
# ACTUAL_URL = "http://actual-REST-URI/v1/budgets/YOUR_BUDGET_ID"
# ACTUAL_API_KEY = "API_KEY"
#
# [categories]
# tfsa_tracking = ["⛱️🍸ATB TFSA", "⛱️🍸Wealthsimple TFSA"]
# Add this new array in the exact order you want them to appear on the dashboard:
# budget_tracking = ["🥡 Eating Out", "🏬 Groceries", "🏢 Office Going Expenses", "⛽ Petrol"]
#
# [resp]
# identifier = "RESP"
# horizon_years = 10
# default_return_pct = 4.0
# monthly_contribution = xxx.0
#
# [rrsp]
# identifier = "RRSP"
# horizon_years = 30
# default_return_pct = 8.0
# annual_contribution = xxx.0
#
# [tfsa]
# horizon_years = 30
# ytd_limit = 7000.0
# annual_room = 7000.0
#
# [tfsa.base]
# identifier = "xxxx"
# default_return_pct = 4.0
# monthly_contribution = 400.0
#
# [tfsa.catchup]
# identifier = "xxxx"
# default_return_pct = 8.0
# catchup_year_contribution = 0.0
# ----------- COPY ABOVE THIS LINE -----------
#
#
# ==============================================================================

version: '3.8'

services:
  actual-dashboard:
    image: preface8675/actual-dashboard:latest  
    container_name: actual-dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - /mnt/Tank/AppData/config/Actual-Dashboard:/app/.streamlit:ro
    environment:
      - PUID=568
      - PGID=3002
      - TZ=America/Edmonton
